import React, { useCallback, useEffect, useState } from 'react';
import { Archive, ArrowRight, BrainCircuit, Box, Code2, Database, FileText, FlaskConical, Globe2, Grid2X2, Home, Image as ImageIcon, LayoutPanelTop, Mail, Network, NotebookPen, Rss, Search, Send, ShieldCheck, Sparkles, Sun, Moon, Terminal, CircleHelp, Clock3, Eye, MessageSquare, Menu, Zap } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import brandLogo from './assets/cats-world-logo-ocean.png';
import heroWorkspace from './assets/hero-workspace.png';
import heroLight from './assets/hero-light-same-cat-daylight.png';
import { AuthScreen } from './auth';
import { contentApi } from './api/client';
import './style.css';

const StudioApp = React.lazy(() => import('./studio').then(module => ({ default: module.StudioApp })));

const nav=[[Home,'首页','/'],[Sparkles,'AI Lab','/posts?q=AI'],[Archive,'故障档案','/posts?q=故障'],[FlaskConical,'实验室','/posts?q=实践'],[ImageIcon,'图库','/posts'],[CircleHelp,'关于','/posts']];
const cats=[[BrainCircuit,'AI 解决方案','320 篇'],[Terminal,'Linux','63 篇'],[Globe2,'网络','28 篇'],[Box,'容器 & 云','19 篇'],[Database,'数据库','9 篇'],[ShieldCheck,'安全','15 篇'],[Code2,'开发','12 篇'],[NotebookPen,'随笔','16 篇']];
const posts=[
 ['AI 实践','用 ChatGPT + Claude 排查服务器 CPU 飙高问题的完整过程','记录一次生产服务器 CPU 异常飙高的排查过程，让 AI 分析日志、定位原因。','AI','Linux','故障排查','2026-09-18','2.3k','12','violet'],
 ['效率提升','让 AI 帮我写 Nginx 反向代理配置并自动优化','从需求描述到可直接使用的 Nginx 配置，记录与 AI 协作的过程。','AI','Nginx','网络','2026-09-15','1.6k','8','blue'],
 ['自动化','用 AI 生成 PostgreSQL 备份与恢复脚本（含权限配置）','给出完整的导出 / 导入脚本，包含角色、权限、模式等配置实践。','AI','PostgreSQL','数据库','2026-09-12','1.4k','10','cyan'],
 ['故障分析','让 AI 帮我分析系统 I/O Hang 的原因和解决方案','从系统日志、内核参数到硬件排查，记录一次服务器 I/O 卡死的分析过程。','AI','Linux','故障排查','2026-09-10','2.1k','9','red'],
 ['配置实践','用 AI 完成 AnyTLS + sing-box 部署方案','从需求说明到完整的部署方案、配置文件和 systemd 脚本的生成过程。','AI','网络','代理','2026-09-07','1.8k','11','navy'],
 ['开发提效','AI 辅助开发：从需求到可运行的数据分类系统','记录使用 AI 完成一个数据分类系统的完整开发过程，包括架构、代码和部署。','AI','开发','Python','2026-09-05','1.3k','7','indigo']
];
const Arrow=()=> <ArrowRight className="arrow" size={16}/>;
function Logo({iconOnly=false, footer=false}){return <span className={'brandLockup '+(footer?'footerLogo':'')+(iconOnly?' iconOnly':'')} aria-label="猫子的世界"><img src={brandLogo} alt="猫子的世界"/></span>}
function Header({lightsOn,onToggle,onStudio,navigate}){const [query,setQuery]=useState('');const [menuOpen,setMenuOpen]=useState(false);const go=(event,to)=>{event.preventDefault();setMenuOpen(false);navigate(to)};return <header className="siteHeader"><div className="wrap nav"><a className="brandAnchor" href="/" onClick={event=>go(event,'/')} aria-label="猫子的世界首页"><span className="desktopBrand"><Logo/></span><span className="mobileBrand"><Logo/></span></a><span className="brandDivider"/><nav className={'primaryNav '+(menuOpen?'mobileOpen':'')}>{nav.map(([,x,to],i)=><a href={to} className={(i?'':'active')+(x==='AI Lab'?' labNav':'')} key={x} onClick={event=>go(event,to)}><NavIcon name={x}/><span>{x}</span></a>)}</nav><div className="navActions"><form className="search navSearch" onSubmit={event=>{event.preventDefault();navigate(`/posts?q=${encodeURIComponent(query.trim())}`)}}><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索文章、标签、问题..." aria-label="搜索文章、标签、问题"/><kbd>⌘ K</kbd></form><button className="sun themeButton" onClick={onToggle} aria-label={lightsOn?'关闭灯光':'打开灯光'}>{lightsOn?<Sun size={18}/>:<Moon size={18}/>}</button><button className="profileButton" aria-label="进入工作台" onClick={onStudio}><span>猫</span><i/></button></div><button className="mobileMenu" onClick={()=>setMenuOpen(value=>!value)} aria-label="打开菜单" aria-expanded={menuOpen}><Menu size={20}/></button></div></header>}
function Hero({lightsOn,postCount,navigate}){return <section className="hero"><div className="heroArt" style={{backgroundImage:`url(${lightsOn?heroLight:heroWorkspace})`}}/><div className="wash"/><div className="wrap heroText"><p className="eyebrow">//　用 AI 解决真实问题</p><h1>让 AI 成为<br/><strong>解决问题的工具</strong></h1><p className="intro">记录用 AI 解决 Linux、网络、运维、开发等<br/>实际问题的过程、思路和经验。<br/>不只是提示词，更关注可落地的方法。</p><div className="stats"><span><b>{postCount ?? '—'}</b>AI 实战文章</span><span><b>50+</b>问题场景</span><span><b>100+</b>可复用方案</span><span><b>持续更新</b>一起探索更多可能</span></div><div className="actions"><button onClick={()=>navigate('/posts')}>浏览 AI 解决方案 <Arrow/></button><button onClick={()=>navigate('/posts')}>查看全部文章</button></div></div></section>}
function AiSolutionsIcon(){return <svg className="aiSolutionsIcon" viewBox="0 0 48 48" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M16 16a8 8 0 0 1 13.4-5.9A8.7 8.7 0 0 1 39 18.7c0 3.1-1.6 5.2-4.1 7.1v3.7a4 4 0 0 1-4 4H29v4.1c0 2.2-1.8 3.9-4 3.9h-2c-2.2 0-4-1.7-4-3.9v-4.1h-1.9a4 4 0 0 1-4-4v-3.7C10.6 23.9 9 21.8 9 18.7a8.7 8.7 0 0 1 7-8.5"/><path d="M16 16h8M24 10v8M30 18h4M24 24v4M18 24h12M20 33.5h8"/><circle cx="16" cy="16" r="1.3" fill="currentColor"/><circle cx="24" cy="10" r="1.3" fill="currentColor"/><circle cx="34" cy="18" r="1.3" fill="currentColor"/></svg>}
function LinuxIcon(){return <svg className="tuxIcon" viewBox="0 0 48 48" aria-hidden="true"><path d="M24 3.5c-8.1 0-12.4 8.4-11.3 18.2L9.2 35.8c-.7 2.8 1.8 5 4.5 3.8l4.5-2 5.8 1.9 5.8-1.9 4.5 2c2.7 1.2 5.2-1 4.5-3.8l-3.5-14.1C36.4 11.9 32.1 3.5 24 3.5Z" fill="#172331"/><path d="M14.2 22.6c1.1-8.5 4.2-14 9.8-14s8.7 5.5 9.8 14l2.1 10.3c.4 1.8-1.2 3.2-2.9 2.4l-4-1.7-5 1.6-5-1.6-4 1.7c-1.7.8-3.3-.6-2.9-2.4l2.1-10.3Z" fill="#263746"/><ellipse cx="24" cy="27.1" rx="9.7" ry="11.1" fill="#f4f7f7"/><path d="M20.2 20.7c.4-1.8 1.7-3 3.8-3s3.4 1.2 3.8 3" fill="none" stroke="#fff" strokeWidth="1.2" strokeLinecap="round"/><ellipse cx="20.2" cy="21.6" rx="2.2" ry="2.6" fill="#fff"/><ellipse cx="27.8" cy="21.6" rx="2.2" ry="2.6" fill="#fff"/><circle cx="20.6" cy="21.9" r=".75" fill="#172331"/><circle cx="27.4" cy="21.9" r=".75" fill="#172331"/><path d="m21.5 25 2.5 2.6 2.5-2.6Z" fill="#f3bc3f"/><path d="M14.8 37.4c-4.1 0-7 1.5-7 3.8 0 1.3 1.1 2.1 2.8 2.1 2.7 0 5.5-1.1 7.8-3.3ZM33.2 37.4c4.1 0 7 1.5 7 3.8 0 1.3-1.1 2.1-2.8 2.1-2.7 0-5.5-1.1-7.8-3.3Z" fill="#f3bc3f"/></svg>}
const officialBrandIcons={
  ChatGPT:['https://api.iconify.design/logos:openai-icon.svg','mono'],
  Claude:['https://api.iconify.design/simple-icons:claude.svg?color=%23e9784f','color'],
  Gemini:['https://api.iconify.design/logos:google-gemini-icon.svg','color'],
  Cursor:['https://api.iconify.design/logos:cursor-icon.svg','mono'],
  Copilot:['https://api.iconify.design/logos:github-copilot.svg','mono']
};
const iconifyToolIcons={
  文档总结:'https://api.iconify.design/ix:document-ai.svg?color=%2354d8ff',
  代码解释:'https://api.iconify.design/tabler:code-ai.svg?color=%2335e1ad',
  Prompt:'https://api.iconify.design/streamline:ai-prompt-spark.svg?color=%23d16dff',
  图像生成:'https://api.iconify.design/streamline:ai-generate-portrait-image-spark.svg?color=%23f4f7fb'
};
const iconifyCategoryIcons={
  'AI 解决方案':'https://api.iconify.design/tabler:ai.svg?color=%23e766eb',
  Linux:'https://api.iconify.design/logos:linux-tux.svg',
  网络:'https://api.iconify.design/tabler:network.svg?color=%2333c5ef',
  '容器 & 云':'https://api.iconify.design/logos:docker-icon.svg',
  数据库:'https://api.iconify.design/tabler:database.svg?color=%236d89ff',
  安全:'https://api.iconify.design/tabler:shield-check.svg?color=%235ce9b8',
  开发:'https://api.iconify.design/tabler:code.svg?color=%23d66cf4',
  随笔:'https://api.iconify.design/tabler:note.svg?color=%23ffbc4d'
};
Object.assign(iconifyCategoryIcons,{
  编程:'https://api.iconify.design/tabler:code.svg?color=%23d66cf4',
  资讯:'https://api.iconify.design/tabler:bulb.svg?color=%23ffbc4d',
  软件:'https://api.iconify.design/tabler:apps.svg?color=%236d89ff',
  运维:'https://api.iconify.design/tabler:server-cog.svg?color=%235ce9b8'
});
const iconifySectionIcons={
  status:'https://api.iconify.design/tabler:bolt.svg?color=%2338e5ad',
  latest:'https://api.iconify.design/tabler:file-ai.svg?color=%2335c7f6',
  tools:'https://api.iconify.design/tabler:ai.svg?color=%23df6ce6',
  tags:'https://api.iconify.design/tabler:tags.svg?color=%23e6f3fc'
};
const iconifyNavIcons={
  首页:'https://api.iconify.design/tabler:home.svg?color=%2349bdff',
  'AI Lab':'https://api.iconify.design/tabler:sparkles.svg?color=%23ca68f0',
  故障档案:'https://api.iconify.design/tabler:archive.svg?color=%23b8c9d9',
  实验室:'https://api.iconify.design/tabler:flask.svg?color=%23b8c9d9',
  图库:'https://api.iconify.design/tabler:photo.svg?color=%23b8c9d9',
  关于:'https://api.iconify.design/tabler:help-circle.svg?color=%23b8c9d9'
};
function NavIcon({name}){return <img className="navIcon" src={iconifyNavIcons[name]} alt="" aria-hidden="true"/>}
function CategoryIcon({name}){const variant=name==='Linux'?' is-linux':name==='容器 & 云'?' is-container':'';return <img className={`categoryIcon${variant}`} src={iconifyCategoryIcons[name]||'https://api.iconify.design/tabler:folder.svg?color=%2333c5ef'} alt="" aria-hidden="true"/>}
function SectionIcon({name}){return <img className="sectionIcon" src={iconifySectionIcons[name]} alt="" aria-hidden="true"/>}
function ToolIcon({name}){
  const official=officialBrandIcons[name];
  if(official) return <img className={`officialBrandIcon ${official[1]}`} src={official[0]} alt="" aria-hidden="true"/>;
  if(iconifyToolIcons[name]) return <img className="iconifyToolIcon" src={iconifyToolIcons[name]} alt="" aria-hidden="true"/>;
  const common={viewBox:'0 0 48 48','aria-hidden':'true'};
  return <ImageIcon {...common} strokeWidth="2.45"/>
}
function Categories({categories=[],statusNodes=[],navigate}){return <section className="wrap categoryArea"><div className="cats">{categories.length?categories.map((item,i)=><button onClick={()=>navigate(`/posts?category=${encodeURIComponent(item.slug)}`)} className={'catCard '+(i?'':'feature')} key={item.id}><CategoryIcon name={item.name}/><b>{item.name}</b><small>{item.postCount} 篇 <Arrow/></small></button>):<p className="dynamicEmpty">暂无分类，导入 Halo 数据或在工作台创建后将在这里显示。</p>}</div>{statusNodes.length>0&&<div className="status"><h3><SectionIcon name="status"/>站点状态 <em><i className="statusPulse" aria-hidden="true"/>正常运行</em></h3>{statusNodes.map(item=><p key={item.id}><i className="statusDot" aria-hidden="true"/>{item.name}<span>{item.latencyMs==null?'待检测':`${item.latencyMs} ms`}</span></p>)}</div>}</section>}
function Post({p,index,navigate}){return <article className="post postLink" tabIndex="0" role="link" onClick={()=>navigate(`/archives/${encodeURIComponent(p.slug)}`)} onKeyDown={event=>event.key==='Enter'&&navigate(`/archives/${encodeURIComponent(p.slug)}`)}><div className={'cover '+['violet','blue','cyan','red','navy','indigo'][index%6]}>{p.coverUrl&&<img className="coverImage" src={p.coverUrl} alt=""/>}<b className="coverBadge">{p.locale==='zh-CN'?'中文':'EN'}</b>{!p.coverUrl&&<div className="screen"><i/><i/><i/><i/></div>}</div><h2>{p.title}</h2><p>{p.summary||'这篇文章暂未提供摘要。'}</p><div className="tags"><span>{p.locale==='zh-CN'?'技术记录':'Technical note'}</span><span>阅读全文 <Arrow/></span></div><footer><span><Clock3/> {p.publishedAt?new Date(p.publishedAt).toLocaleDateString('zh-CN'):'草稿'}</span><span><Eye/> 阅读</span></footer></article>}
function Side({tags=[],tools=[],navigate}){return <aside>{tools.length>0&&<section className="panel"><h3><SectionIcon name="tools"/>常用 AI 工具 <a href="/posts" onClick={event=>{event.preventDefault();navigate('/posts')}}>更多工具 <Arrow/></a></h3><div className="tools">{tools.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.id}><span className="toolIcon"><ToolIcon name={item.name}/></span><b>{item.name}</b><small>{item.description||'AI 工具'}</small></a>)}</div></section>}{tags.length>0&&<section className="panel tagsPanel"><h3><SectionIcon name="tags"/>热门标签 <a href="/posts" onClick={event=>{event.preventDefault();navigate('/posts')}}>查看全部 <Arrow/></a></h3><div>{tags.map(item=><button onClick={()=>navigate(`/posts?q=${encodeURIComponent(item.name)}`)} key={item.id}>{item.name}　{item.postCount}</button>)}</div></section>}<button className="journey" onClick={()=>navigate('/studio')}><Logo iconOnly/><span><b>加入我的旅程</b><small>记录、分享、成长</small></span><Arrow/></button></aside>}
function Main({home,navigate}){const items=home?.posts||[];return <main className="wrap main"><section><div className="heading"><h2><SectionIcon name="latest"/>最新 AI 解决方案</h2><a href="/posts" onClick={event=>{event.preventDefault();navigate('/posts')}}>查看全部 <Arrow/></a></div>{items.length?<div className="posts">{items.map((item,index)=><Post p={item} index={index} navigate={navigate} key={item.id}/>)}</div>:<p className="dynamicEmpty">暂无已发布文章。</p>}<div className="quote"><b>“</b><span>AI 不是替代思考，而是放大解决问题的能力。<small>— 某个晚上</small></span><i>Better Prompts<br/>Bigger Solutions.</i></div></section><Side tags={home?.tags} tools={home?.tools} navigate={navigate}/></main>}
function Footer(){return <footer><div className="wrap foot"><nav>首页　　AI Lab　　故障档案　　实验室　　图库　　关于</nav><span className="footerSocial" aria-label="社交链接"><img className="footerGithub" src="https://api.iconify.design/tabler:brand-github.svg?color=%239ab7cb" alt="GitHub"/><Rss/><Mail/><Send/></span></div><div className="wrap copyright"><span>© 2026. All rights reserved.</span><span className="footerBrand"><Logo footer/>记录技术，也记录生活。</span><a className="icpRecord">ICP备案号：待补充</a><span className="footerSlogan">用技术让生活更有趣。</span></div></footer>}
function PublicShell({children,lightsOn,onToggle,navigate}){return <div className={'appShell '+(lightsOn?'lightsOn':'')}><Header lightsOn={lightsOn} onToggle={onToggle} onStudio={()=>navigate('/studio')} navigate={navigate}/>{children}<Footer/></div>}
function ListRow({post,navigate}){const date=post.publishedAt?new Date(post.publishedAt):null;return <article className="listRow" role="link" tabIndex="0" onClick={()=>navigate(`/archives/${encodeURIComponent(post.slug)}`)} onKeyDown={event=>event.key==='Enter'&&navigate(`/archives/${encodeURIComponent(post.slug)}`)}><time>{date?<><b>{String(date.getMonth()+1).padStart(2,'0')}-{String(date.getDate()).padStart(2,'0')}</b><span>{date.getFullYear()}</span></>:<b>草稿</b>}</time><div className="listCopy"><h2>{post.title}</h2><p>{post.summary||'这篇文章暂未提供摘要。'}</p><div><span>技术记录</span><span>{post.locale==='zh-CN'?'中文':'English'}</span><em><Eye size={14}/> 阅读文章</em></div></div>{post.coverUrl?<img src={post.coverUrl} alt=""/>:<div className="listNoCover"><FileText size={24}/></div>}</article>}
function PublicSidebar({home,navigate}){return <aside className="publicSidebar">{(home?.statusNodes||[]).length>0&&<section className="sidebarStatus"><h3><SectionIcon name="status"/>当前状态 <em><i/>全部正常</em></h3>{home.statusNodes.map(item=><p key={item.id}><i/>{item.name}<small>{item.latencyMs==null?'—':`${item.latencyMs} ms`}</small></p>)}</section>}<section><h3>正在探索</h3><div className="exploreLinks">{(home?.categories||[]).slice(0,6).map(item=><button key={item.id} onClick={()=>navigate(`/posts?category=${encodeURIComponent(item.slug)}`)}>→　{item.name}<small>{item.postCount}</small></button>)}</div></section><section><h3>热门标签</h3><div className="sidebarTags">{(home?.tags||[]).slice(0,14).map(item=><button key={item.id} onClick={()=>navigate(`/posts?q=${encodeURIComponent(item.name)}`)}>{item.name}<small>{item.postCount}</small></button>)}</div></section><section className="sidebarQuote"><b>“</b><p>把复杂的问题，拆成每一次可验证的实践。<small>— HZCAT</small></p></section></aside>}
function PostListScreen({lightsOn,onToggle,navigate}){const params=new URLSearchParams(window.location.search);const q=params.get('q')||'';const category=params.get('category')||'';const [state,setState]=useState({loading:true,items:[],error:''});const [home,setHome]=useState(null);useEffect(()=>{let active=true;setState({loading:true,items:[],error:''});Promise.all([contentApi.posts({q,category,pageSize:'20'}),contentApi.home()]).then(([posts,homepage])=>{if(!active)return;setState({loading:false,items:posts.data,error:''});setHome(homepage.data)}).catch(error=>active&&setState({loading:false,items:[],error:error.message||'文章列表加载失败。'}));return()=>{active=false}},[q,category]);const title=q?`搜索：${q}`:category?'分类文章':'最新文章';return <PublicShell lightsOn={lightsOn} onToggle={onToggle} navigate={navigate}><main className="wrap listingPage"><header className="listingHead"><p>//　技术笔记</p><h1>{title}</h1><span>共记录 {state.items.length || '—'} 篇内容，以问题、过程和可复用方案为线索。</span></header><div className="listingLayout"><section className="articleList">{state.error?<p className="dynamicError">{state.error}</p>:state.loading?<p className="dynamicEmpty">正在加载文章…</p>:state.items.length?state.items.map(item=><ListRow post={item} navigate={navigate} key={item.id}/>):<p className="dynamicEmpty">没有匹配的已发布文章。</p>}</section><PublicSidebar home={home} navigate={navigate}/></div></main></PublicShell>}
function contentText(value){if(typeof value==='string')return value;if(value==null)return '';try{return JSON.stringify(value)}catch{return ''}}
function legacyHaloText(content){const source=contentText(content);try{const patches=JSON.parse(source);if(!Array.isArray(patches))return source;const html=patches.map(item=>item?.target?.lines?.join('\n')||'').join('\n');return new DOMParser().parseFromString(html,'text/html').body.textContent?.trim()||source}catch{return source}}
function InlineMarkdown({value}){const parts=value.split(/(\[[^\]]+\]\([^\s)]+\)|`[^`]+`|\*\*[^*]+\*\*)/g);return <>{parts.map((part,index)=>{const link=part.match(/^\[([^\]]+)\]\(([^\s)]+)\)$/);if(link){const safe=/^https?:\/\//i.test(link[2]);return safe?<a key={index} href={link[2]} target="_blank" rel="noreferrer">{link[1]}</a>:link[1]}if(part.startsWith('`')&&part.endsWith('`'))return <code key={index}>{part.slice(1,-1)}</code>;if(part.startsWith('**')&&part.endsWith('**'))return <strong key={index}>{part.slice(2,-2)}</strong>;return part})}</>}
function articleHeadings(content){return contentText(content).replace(/\r\n/g,'\n').split('\n').map(line=>line.match(/^(#{1,6})\s+(.+)/)).filter(Boolean).slice(0,14).map((match,index)=>({id:`section-${index}`,depth:Math.min(match[1].length,4),title:match[2]}))}
function MarkdownBody({content,headings=[]}){const lines=contentText(content).replace(/\r\n/g,'\n').split('\n');const blocks=[];let index=0;let headingIndex=0;while(index<lines.length){const line=lines[index];if(!line.trim()){index+=1;continue}if(/^```/.test(line.trim())){const code=[];index+=1;while(index<lines.length&&!/^```/.test(lines[index].trim())){code.push(lines[index]);index+=1}index+=1;blocks.push(<pre key={`code-${index}`}><code>{code.join('\n')}</code></pre>);continue}const heading=line.match(/^(#{1,6})\s+(.+)/);if(heading){const Tag=`h${Math.min(heading[1].length+1,4)}`;const headingId=headings[headingIndex++]?.id;blocks.push(<Tag id={headingId} key={`heading-${index}`}><InlineMarkdown value={heading[2]}/></Tag>);index+=1;continue}const image=line.match(/^!\[([^\]]*)\]\(([^\s)]+)\)$/);if(image){blocks.push(<img className="articleInlineImage" key={`image-${index}`} src={image[2]} alt={image[1]||''}/>);index+=1;continue}if(/^[-*]\s+/.test(line)){const items=[];while(index<lines.length&&/^[-*]\s+/.test(lines[index])){items.push(<li key={index}><InlineMarkdown value={lines[index].replace(/^[-*]\s+/, '')}/></li>);index+=1}blocks.push(<ul key={`list-${index}`}>{items}</ul>);continue}const paragraph=[];while(index<lines.length&&lines[index].trim()&&!/^```/.test(lines[index].trim())&&!/^(#{1,6})\s+/.test(lines[index])&&!/^!\[/.test(lines[index])&&!/^[-*]\s+/.test(lines[index])){paragraph.push(lines[index]);index+=1}blocks.push(<p key={`paragraph-${index}`}><InlineMarkdown value={paragraph.join(' ')}/></p>)}return <div className="articleBody">{blocks}</div>}
function sanitizedHtml(content){const document=new DOMParser().parseFromString(contentText(content),'text/html');document.querySelectorAll('script,style,iframe,object,embed,link,meta,base,form,input,button').forEach(node=>node.remove());document.querySelectorAll('*').forEach(node=>{[...node.attributes].forEach(attribute=>{const name=attribute.name.toLowerCase();const value=attribute.value.trim();const allowedUrl=/^(https?:|mailto:|#|\/)/i.test(value);if(name.startsWith('on')||((name==='href'||name==='src')&&!allowedUrl))node.removeAttribute(attribute.name)})});return document.body.innerHTML}
function HtmlBody({content}){return <div className="articleBody htmlArticleBody" dangerouslySetInnerHTML={{__html:sanitizedHtml(content)}}/>}
function ArticleScreen({slug,lightsOn,onToggle,navigate}){const [state,setState]=useState({loading:true,item:null,error:''});const [home,setHome]=useState(null);useEffect(()=>{let active=true;Promise.all([contentApi.post(slug),contentApi.home()]).then(([post,homepage])=>active&&((setState({loading:false,item:post.data,error:''})),setHome(homepage.data))).catch(error=>active&&setState({loading:false,item:null,error:error.message||'文章加载失败。'}));return()=>{active=false}},[slug]);const item=state.item;const isHtml=item?.contentFormat==='html';const body=item?(isHtml?contentText(item.content||''):legacyHaloText(item.content||'')):'';const headings=isHtml?[]:articleHeadings(body);return <PublicShell lightsOn={lightsOn} onToggle={onToggle} navigate={navigate}><main className="wrap articlePage">{state.loading?<p className="dynamicEmpty">正在加载文章…</p>:state.error?<><button className="backButton" onClick={()=>navigate('/posts')}>← 返回文章列表</button><p className="dynamicError">{state.error}</p></>:<div className="articleLayout"><aside className="articleLeftRail"><h3>分类</h3>{(home?.categories||[]).map(category=><button key={category.id} onClick={()=>navigate(`/posts?category=${encodeURIComponent(category.slug)}`)}><CategoryIcon name={category.name}/><span>{category.name}</span><small>{category.postCount}</small></button>)}</aside><article className="articleDocument"><button className="backButton" onClick={()=>navigate('/posts')}>← 返回文章列表</button><p className="eyebrow">{item.locale==='zh-CN'?'技术笔记':'Technical note'}　/　{item.publishedAt?new Date(item.publishedAt).toLocaleDateString('zh-CN'):'草稿'}</p><h1>{item.title}</h1>{item.summary&&<p className="articleSummary">{item.summary}</p>}<div className="articleMeta"><span><Clock3/> {item.publishedAt?new Date(item.publishedAt).toLocaleDateString('zh-CN'):'草稿'}</span><span><Eye/> 阅读文章</span></div>{item.coverUrl&&<img className="articleCover" src={item.coverUrl} alt=""/>}{isHtml?<HtmlBody content={body}/>:<MarkdownBody content={body} headings={headings}/>}</article><aside className="articleRightRail"><section><h3>目录</h3>{headings.length?headings.map(item=><a className={`depth-${item.depth}`} href={`#${item.id}`} key={item.id}>{item.title}</a>):<p>{isHtml?'HTML 文章暂不生成目录。':'本文暂无目录。'}</p>}</section><section><h3>热门标签</h3><div className="sidebarTags">{(home?.tags||[]).slice(0,10).map(tag=><button key={tag.id} onClick={()=>navigate(`/posts?q=${encodeURIComponent(tag.name)}`)}>{tag.name}<small>{tag.postCount}</small></button>)}</div></section></aside></div>}</main></PublicShell>}
function App(){const [lightsOn,setLightsOn]=useState(false);const [location,setLocation]=useState(()=>window.location.pathname+window.location.search);const [home,setHome]=useState(null);const [homeError,setHomeError]=useState('');const navigate=useCallback((to)=>{const target=to||'/';if(window.location.pathname+window.location.search!==target)window.history.pushState({},'',target);setLocation(target);window.scrollTo({top:0,behavior:'auto'});},[]);useEffect(()=>{const update=()=>setLocation(window.location.pathname+window.location.search);window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);useEffect(()=>{let active=true;contentApi.home().then((result)=>active&&setHome(result.data)).catch(()=>active&&setHomeError('首页数据暂时无法加载。'));return()=>{active=false};},[]);const pathname=location.split('?')[0];if(pathname==='/login')return <AuthScreen mode="login" navigate={navigate}/>;if(pathname==='/register')return <AuthScreen mode="register" navigate={navigate}/>;if(pathname==='/studio'||pathname.startsWith('/studio/'))return <React.Suspense fallback={<main className="studioLoading">正在加载工作台…</main>}><StudioApp navigate={navigate}/></React.Suspense>;if(pathname==='/posts')return <PostListScreen lightsOn={lightsOn} onToggle={()=>setLightsOn(value=>!value)} navigate={navigate}/>;if(pathname.startsWith('/archives/'))return <ArticleScreen slug={decodeURIComponent(pathname.slice('/archives/'.length))} lightsOn={lightsOn} onToggle={()=>setLightsOn(value=>!value)} navigate={navigate}/>;return <PublicShell lightsOn={lightsOn} onToggle={()=>setLightsOn(value=>!value)} navigate={navigate}><Hero lightsOn={lightsOn} postCount={home?.postCount} navigate={navigate}/>{homeError&&<p className="wrap dynamicError">{homeError}</p>}<Categories categories={home?.categories} statusNodes={home?.statusNodes} navigate={navigate}/><Main home={home} navigate={navigate}/></PublicShell>}
createRoot(document.getElementById('root')).render(<App/>);
